version: "3"
services:
  php:
    build:
      args:
        UID: ${UID-1000}
        GID: ${GID-1000}
      context: ./docker
    command: sh
    environment:
      SKIP_DOCKER: "true" 
    tty: true
    stdin_open: true
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - .:/home/dev/pkg

  flextesa:
    image: "tqtezos/flextesa:20201214"
    command: edobox start 
    ports:
      - "8732:20000"
    environment:
      - block_time=1
      - flextesa_node_cors_origin=*
    volumes:
      - ./tezos-client.config.json:/root/.tezos-client/config

